<a href="https://colab.research.google.com/github/yanin-dev/mineria-de-datos/blob/main/Copia_de_CONCONCAT_ULT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
from google.colab import drive
# Esto montará tu Google Drive en el directorio '/content/drive'
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [86]:
# Reemplazá estas rutas por las rutas reales de tus archivos
ruta_1 = '/content/drive/MyDrive/mineriadatos2026/dataset-mineria/clientes_crm.csv'
ruta_2 = '/content/drive/MyDrive/mineriadatos2026/dataset-mineria/newsletter.csv'
ruta_3 = '/content/drive/MyDrive/mineriadatos2026/dataset-mineria/soporte.csv'
ruta_4 = '/content/drive/MyDrive/mineriadatos2026/dataset-mineria/ventas.csv'

# Leer los 4 archivos usando read_csv ya que son archivos CSV
df1 = pd.read_csv(ruta_1)
df2 = pd.read_csv(ruta_2)
df3 = pd.read_csv(ruta_3)
df4 = pd.read_csv(ruta_4)

# Verificar la carga
print("clientes_crm:", df1.shape)
print("newsletter:", df2.shape)
print("soporte:", df3.shape)
print("ventas:", df4.shape)

clientes_crm: (433, 13)
newsletter: (325, 6)
soporte: (566, 7)
ventas: (1626, 9)

In [87]:
from pathlib import Path

def buscar_csv(comienzo_del_nombre):
    encontrados = list(Path('.').glob(comienzo_del_nombre + '*.csv'))
    if len(encontrados) == 0:
        raise FileNotFoundError('No se encontró: ' + comienzo_del_nombre)
    return encontrados[0]

In [88]:
import pandas as pd

In [89]:
crm = pd.read_csv(buscar_csv('clientes_crm'))
ventas = pd.read_csv(buscar_csv('ventas'))
soporte = pd.read_csv(buscar_csv('soporte'))
newsletter = pd.read_csv(buscar_csv('newsletter'))
# zonas = pd.read_csv(buscar_csv('zonas_caba'))
# distancias = pd.read_csv(buscar_csv('distancias_sedes'))

print('Los seis archivos fueron cargados correctamente.')

Los seis archivos fueron cargados correctamente.

In [90]:
import unicodedata
import re

def limpiar_nombre(nombre):
    if pd.isna(nombre):
        return None

    nombre = nombre.lower().strip()

    nombre = unicodedata.normalize("NFD", nombre)
    nombre = "".join(
        letra for letra in nombre
        if unicodedata.category(letra) != "Mn"
    )

    nombre = re.sub(r"\s+", " ", nombre)

    return nombre

def limpiar_dni(valor):

    if pd.isna(valor):
        return pd.NA

    cont = 0
    valor = str(valor)
    new_valor = ""

    for i in valor:

        if i.isdigit():
            cont += 1
            new_valor += i

    if cont == 8:
        return new_valor
    else:
        return pd.NA

def limpiar_email(valor): #a@@a.com -> a@a.com
    if pd.isna(valor):
        return pd.NA

    email = str(valor).strip().lower()

    while "@@" in email:
      email = email.replace("@@", "@")

    if '@' not in email:
        return pd.NA
    else:
        return email

In [91]:
crm.columns

Index(['crm_id', 'dni', 'nombre', 'email', 'telefono', 'fecha_nacimiento',
       'edad', 'genero', 'provincia', 'codigo_postal', 'segmento',
       'fecha_alta', 'ingreso_mensual'],
      dtype='object')

In [92]:
ventas.columns

Index(['venta_id', 'documento_cliente', 'cliente', 'correo', 'fecha_compra',
       'monto', 'moneda', 'canal', 'cantidad_items'],
      dtype='object')

In [93]:
soporte.columns

Index(['ticket_id', 'documento', 'nombre_cliente', 'email_contacto',
       'fecha_ticket', 'tipo', 'satisfaccion'],
      dtype='object')

In [94]:
newsletter.columns

Index(['suscriptor_id', 'email', 'nombre', 'estado', 'aperturas_90d',
       'clicks_90d'],
      dtype='object')

In [95]:
df_crm = crm.copy()
df_ventas = ventas.copy()
df_soporte = soporte.copy()
df_news = newsletter.copy()

In [96]:
df_ventas.rename(columns={"documento_cliente": "dni", "cliente": "nombre", "correo": "email"}, inplace=True)
df_soporte.rename(columns={"documento": "dni", "nombre_cliente": "nombre", "email_contacto": "email"}, inplace=True)

In [97]:
df_total = pd.concat([df_crm, df_ventas, df_soporte, df_news], ignore_index=True)

In [98]:
df_total.shape

(2950, 27)

In [99]:
pd.set_option('display.max_columns', None)

In [100]:
df_total.head(1)

,crm_id,dni,nombre,email,telefono,fecha_nacimiento,edad,genero,provincia,codigo_postal,segmento,fecha_alta,ingreso_mensual,venta_id,fecha_compra,monto,moneda,canal,cantidad_items,ticket_id,fecha_ticket,tipo,satisfaccion,suscriptor_id,estado,aperturas_90d,clicks_90d
0,CRM0001,44-232-252,Sebastian Medina,sebastian.medina.32@outlook.com,1162280334,10/05/1962,64.0,H,CABA,C1428,PyME,05/09/2024,256744.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
df_total["nombre_limpio"] = df_total["nombre"].apply(limpiar_nombre)
df_total["dni_limpio"] = df_total["dni"].apply(limpiar_dni)
df_total["email_limpio"] = df_total["email"].apply(limpiar_email)

In [102]:
df_total.shape

(2950, 30)

In [103]:
df_total = df_total.drop_duplicates(subset=["dni_limpio", "email_limpio", "nombre_limpio"])

In [104]:
df_total.shape

(1299, 30)

In [105]:
df_total.isnull().sum()

crm_id               869
dni                  411
nombre                 0
email                218
telefono             889
fecha_nacimiento     869
edad                 869
genero               874
provincia            869
codigo_postal        869
segmento             869
fecha_alta           869
ingreso_mensual      883
venta_id             799
fecha_compra         799
monto                799
moneda               799
canal                799
cantidad_items       799
ticket_id           1170
fecha_ticket        1170
tipo                1170
satisfaccion        1213
suscriptor_id       1059
estado              1059
aperturas_90d       1059
clicks_90d          1059
nombre_limpio          0
dni_limpio           420
email_limpio         226
dtype: int64

In [106]:
df_total_con_dni = df_total[df_total["dni_limpio"].notna()].copy()

In [107]:
df_total_con_dni.isnull().sum()

crm_id              462
dni                   0
nombre                0
email               185
telefono            480
fecha_nacimiento    462
edad                462
genero              467
provincia           462
codigo_postal       462
segmento            462
fecha_alta          462
ingreso_mensual     476
venta_id            500
fecha_compra        500
monto               500
moneda              500
canal               500
cantidad_items      500
ticket_id           796
fecha_ticket        796
tipo                796
satisfaccion        825
suscriptor_id       879
estado              879
aperturas_90d       879
clicks_90d          879
nombre_limpio         0
dni_limpio            0
email_limpio        192
dtype: int64

In [108]:
df_total_con_dni.shape

(879, 30)

In [109]:
df_total_con_dni["dni_limpio"].nunique()

498

In [110]:
nombres_por_dni = df_total_con_dni.groupby("dni_limpio")["nombre_limpio"].apply(list)

In [111]:
nombres_por_dni

dni_limpio
20003195                                    [agustina castro]
20084930                                     [carolina rojas]
20179048                     [micaela acosta, micaela acosta]
20315891                                     [andres benitez]
20427454                                      [nicolas rojas]
                                  ...
49803465    [sofia ruiz, sofia federico ruiz, sofia federi...
49806301                         [camila silva, camila silva]
49827543                     [carolina gomez, carolina gomez]
49924653           [paula rodriguez, paula julieta rodriguez]
49976237        [matias medina, matias medina, matias medina]
Name: nombre_limpio, Length: 498, dtype: object

In [112]:
emails_por_dni = df_total_con_dni.groupby("dni_limpio")["email_limpio"].apply(list)

In [113]:
emails_por_dni

dni_limpio
20003195                     [agustina.castro.90@hotmail.com]
20084930                      [carolina.rojas.43@outlook.com]
20179048                [micaela.acosta.82@hotmail.com, <NA>]
20315891                      [andres.benitez.68@hotmail.com]
20427454                         [nicolas.rojas.15@gmail.com]
                                  ...
49803465    [sofia.federico.ruiz.81@gmail.com, sofiafederi...
49806301                    [camila.silva.30@gmail.com, <NA>]
49827543                [carolina.gomez.46@outlook.com, <NA>]
49924653    [paula.julieta.rodriguez.42@gmail.com, paula.j...
49976237    [matias.medina.10@outlook.com, <NA>, matiasmed...
Name: email_limpio, Length: 498, dtype: object

In [114]:
df_total_con_dni["nombres_asociados"] = (df_total_con_dni["dni_limpio"].map(nombres_por_dni))
df_total_con_dni["emails_asociados"] = (df_total_con_dni["dni_limpio"].map(emails_por_dni))

In [115]:
df_total_con_dni.shape

(879, 32)

In [116]:
df_total_con_dni = df_total_con_dni.drop_duplicates(subset=["dni_limpio"])

In [117]:
df_total_con_dni.shape

(498, 32)

In [118]:
df_total_sin_dni_con_email = df_total[df_total["dni_limpio"].isna() & ~df_total["email_limpio"].isna()].copy()

In [119]:
df_total_sin_dni_con_email.isnull().sum()

crm_id              373
dni                 377
nombre                0
email                 0
telefono            375
fecha_nacimiento    373
edad                373
genero              373
provincia           373
codigo_postal       373
segmento            373
fecha_alta          373
ingreso_mensual     373
venta_id            283
fecha_compra        283
monto               283
moneda              283
canal               283
cantidad_items      283
ticket_id           345
fecha_ticket        345
tipo                345
satisfaccion        358
suscriptor_id       157
estado              157
aperturas_90d       157
clicks_90d          157
nombre_limpio         0
dni_limpio          386
email_limpio          0
dtype: int64

In [120]:
df_total_sin_dni_con_email.shape

(386, 30)

In [121]:
df_total_sin_dni_con_email = df_total_sin_dni_con_email[~df_total_sin_dni_con_email["email_limpio"].isin(df_total_con_dni["email_limpio"].dropna())]

In [122]:
df_total_sin_dni_con_email.shape

(56, 30)

In [123]:
emails_asociados_explode = df_total_con_dni["emails_asociados"].dropna().explode()

In [124]:
df_total_sin_dni_con_email = df_total_sin_dni_con_email[~df_total_sin_dni_con_email["email_limpio"].isin(emails_asociados_explode.dropna())]

In [125]:
df_total_sin_dni_con_email.shape

(31, 30)

In [126]:
df_total_final = pd.concat([df_total_con_dni, df_total_sin_dni_con_email], ignore_index=True)

In [127]:
df_total_final.shape

(529, 32)

In [128]:
df_total_final.head(1)

,crm_id,dni,nombre,email,telefono,fecha_nacimiento,edad,genero,provincia,codigo_postal,segmento,fecha_alta,ingreso_mensual,venta_id,fecha_compra,monto,moneda,canal,cantidad_items,ticket_id,fecha_ticket,tipo,satisfaccion,suscriptor_id,estado,aperturas_90d,clicks_90d,nombre_limpio,dni_limpio,email_limpio,nombres_asociados,emails_asociados
0,CRM0001,44-232-252,Sebastian Medina,sebastian.medina.32@outlook.com,1162280334,10/05/1962,64.0,H,CABA,C1428,PyME,05/09/2024,256744.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sebastian medina,44232252,sebastian.medina.32@outlook.com,"[sebastian medina, sebastian medina]","[sebastian.medina.32@outlook.com, <NA>]"

In [129]:
df_total_sin_dni_sin_email = df_total[df_total["dni_limpio"].isna() & df_total["email_limpio"].isna()].copy()

In [130]:
df_total_sin_dni_sin_email.shape

(34, 30)

In [131]:
df_total_sin_dni_sin_email = df_total_sin_dni_sin_email.drop_duplicates()

In [132]:
df_total_sin_dni_sin_email.shape

(34, 30)

In [133]:
df_total_final = df_total_final.sort_values(["dni_limpio", "email_limpio"])

In [134]:
df_total_final["cliente_id"] = [i for i in range(1,len(df_total_final)+1)]

In [135]:
df_total_final.head(5)

,crm_id,dni,nombre,email,telefono,fecha_nacimiento,edad,genero,provincia,codigo_postal,segmento,fecha_alta,ingreso_mensual,venta_id,fecha_compra,monto,moneda,canal,cantidad_items,ticket_id,fecha_ticket,tipo,satisfaccion,suscriptor_id,estado,aperturas_90d,clicks_90d,nombre_limpio,dni_limpio,email_limpio,nombres_asociados,emails_asociados,cliente_id
116,CRM0123,20-003-195,Agustina Castro,agustina.castro.90@hotmail.com,1168172895,1949-03-18,77.0,f,CABA,C1425,PyME,21-10-24,528903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,agustina castro,20003195,agustina.castro.90@hotmail.com,[agustina castro],[agustina.castro.90@hotmail.com],1
284,CRM0294,20084930,CAROLINA ROJAS,CAROLINA.ROJAS.43@OUTLOOK.COM,1168929949,21/08/1980,46.0,f,Entre Ríos,E3100,Particular,11/08/2023,499371.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carolina rojas,20084930,carolina.rojas.43@outlook.com,[carolina rojas],[carolina.rojas.43@outlook.com],2
169,CRM0177,20-179-048,Micaela Acosta,micaela.acosta.82@hotmail.com,1160551066,10/09/1970,55.0,f,Buenos Aires,E3100,Empresa,20/03/2022,379683.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,micaela acosta,20179048,micaela.acosta.82@hotmail.com,"[micaela acosta, micaela acosta]","[micaela.acosta.82@hotmail.com, <NA>]",3
290,CRM0300,20315891,ANDRES BENITEZ,andres.benitez.68@hotmail.com,1137355219,17-11-07,18.0,Masculino,CABA,C1431,Particular,24-07-24,735737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,andres benitez,20315891,andres.benitez.68@hotmail.com,[andres benitez],[andres.benitez.68@hotmail.com],4
190,CRM0198,20427454,Nicolas Rojas,nicolas.rojas.15@gmail.com,NaN,1971-12-28,54.0,D,Córdoba,E3100,Particular,14-03-25,570242.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nicolas rojas,20427454,nicolas.rojas.15@gmail.com,[nicolas rojas],[nicolas.rojas.15@gmail.com],5

In [136]:
df_total_final.insert(0, "cliente_id", df_total_final.pop("cliente_id"))

In [137]:
df_total_final.tail()

,cliente_id,crm_id,dni,nombre,email,telefono,fecha_nacimiento,edad,genero,provincia,codigo_postal,segmento,fecha_alta,ingreso_mensual,venta_id,fecha_compra,monto,moneda,canal,cantidad_items,ticket_id,fecha_ticket,tipo,satisfaccion,suscriptor_id,estado,aperturas_90d,clicks_90d,nombre_limpio,dni_limpio,email_limpio,nombres_asociados,emails_asociados
516,525,NaN,NaN,Tomas A. Castro,tomasandrescastro35@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0102,rebote,6.0,3.0,tomas a. castro,<NA>,tomasandrescastro35@hotmail.com,NaN,NaN
503,526,NaN,NaN,Tomas A. Torres,tomasandrestorres70@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00383,05-07-26,Consulta,1.0,NaN,NaN,NaN,NaN,tomas a. torres,<NA>,tomasandrestorres70@hotmail.com,NaN,NaN
528,527,NaN,NaN,Tomas Romero,tomasromero76@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0320,activo,8.0,1.0,tomas romero,<NA>,tomasromero76@outlook.com,NaN,NaN
520,528,NaN,NaN,Tomas Silva,tomassilva81@empresa.com.ar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0162,activo,2.0,1.0,tomas silva,<NA>,tomassilva81@empresa.com.ar,NaN,NaN
501,529,NaN,NaN,Valentina Benitez,valentina.benitez.52@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V001440,20-08-25,20174.93,ARS,Tienda,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,valentina benitez,<NA>,valentina.benitez.52@outlook.com,NaN,NaN

In [138]:
df_total_final.reset_index(drop=True, inplace=True)

In [139]:
df_total_final

,cliente_id,crm_id,dni,nombre,email,telefono,fecha_nacimiento,edad,genero,provincia,codigo_postal,segmento,fecha_alta,ingreso_mensual,venta_id,fecha_compra,monto,moneda,canal,cantidad_items,ticket_id,fecha_ticket,tipo,satisfaccion,suscriptor_id,estado,aperturas_90d,clicks_90d,nombre_limpio,dni_limpio,email_limpio,nombres_asociados,emails_asociados
0,1,CRM0123,20-003-195,Agustina Castro,agustina.castro.90@hotmail.com,1168172895,1949-03-18,77.0,f,CABA,C1425,PyME,21-10-24,528903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,agustina castro,20003195,agustina.castro.90@hotmail.com,[agustina castro],[agustina.castro.90@hotmail.com]
1,2,CRM0294,20084930,CAROLINA ROJAS,CAROLINA.ROJAS.43@OUTLOOK.COM,1168929949,21/08/1980,46.0,f,Entre Ríos,E3100,Particular,11/08/2023,499371.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carolina rojas,20084930,carolina.rojas.43@outlook.com,[carolina rojas],[carolina.rojas.43@outlook.com]
2,3,CRM0177,20-179-048,Micaela Acosta,micaela.acosta.82@hotmail.com,1160551066,10/09/1970,55.0,f,Buenos Aires,E3100,Empresa,20/03/2022,379683.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,micaela acosta,20179048,micaela.acosta.82@hotmail.com,"[micaela acosta, micaela acosta]","[micaela.acosta.82@hotmail.com, <NA>]"
3,4,CRM0300,20315891,ANDRES BENITEZ,andres.benitez.68@hotmail.com,1137355219,17-11-07,18.0,Masculino,CABA,C1431,Particular,24-07-24,735737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,andres benitez,20315891,andres.benitez.68@hotmail.com,[andres benitez],[andres.benitez.68@hotmail.com]
4,5,CRM0198,20427454,Nicolas Rojas,nicolas.rojas.15@gmail.com,NaN,1971-12-28,54.0,D,Córdoba,E3100,Particular,14-03-25,570242.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nicolas rojas,20427454,nicolas.rojas.15@gmail.com,[nicolas rojas],[nicolas.rojas.15@gmail.com]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,525,NaN,NaN,Tomas A. Castro,tomasandrescastro35@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0102,rebote,6.0,3.0,tomas a. castro,<NA>,tomasandrescastro35@hotmail.com,NaN,NaN
525,526,NaN,NaN,Tomas A. Torres,tomasandrestorres70@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00383,05-07-26,Consulta,1.0,NaN,NaN,NaN,NaN,tomas a. torres,<NA>,tomasandrestorres70@hotmail.com,NaN,NaN
526,527,NaN,NaN,Tomas Romero,tomasromero76@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0320,activo,8.0,1.0,tomas romero,<NA>,tomasromero76@outlook.com,NaN,NaN
527,528,NaN,NaN,Tomas Silva,tomassilva81@empresa.com.ar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0162,activo,2.0,1.0,tomas silva,<NA>,tomassilva81@empresa.com.ar,NaN,NaN
528,529,NaN,NaN,Valentina Benitez,valentina.benitez.52@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V001440,20-08-25,20174.93,ARS,Tienda,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,valentina benitez,<NA>,valentina.benitez.52@outlook.com,NaN,NaN

In [140]:
for i, j in df_total_final.iterrows():

    # Si emails_asociados no es una lista
    if not isinstance(j["emails_asociados"], list):
        df_total_final.at[i, "emails_asociados"] = []

    # Si hay un email limpio, lo agregamos si todavía no está
    if pd.notna(j["email_limpio"]):
        if j["email_limpio"] not in df_total_final.at[i, "emails_asociados"]:
            df_total_final.at[i, "emails_asociados"].append(j["email_limpio"])

In [141]:
df_total_final

,cliente_id,crm_id,dni,nombre,email,telefono,fecha_nacimiento,edad,genero,provincia,codigo_postal,segmento,fecha_alta,ingreso_mensual,venta_id,fecha_compra,monto,moneda,canal,cantidad_items,ticket_id,fecha_ticket,tipo,satisfaccion,suscriptor_id,estado,aperturas_90d,clicks_90d,nombre_limpio,dni_limpio,email_limpio,nombres_asociados,emails_asociados
0,1,CRM0123,20-003-195,Agustina Castro,agustina.castro.90@hotmail.com,1168172895,1949-03-18,77.0,f,CABA,C1425,PyME,21-10-24,528903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,agustina castro,20003195,agustina.castro.90@hotmail.com,[agustina castro],[agustina.castro.90@hotmail.com]
1,2,CRM0294,20084930,CAROLINA ROJAS,CAROLINA.ROJAS.43@OUTLOOK.COM,1168929949,21/08/1980,46.0,f,Entre Ríos,E3100,Particular,11/08/2023,499371.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carolina rojas,20084930,carolina.rojas.43@outlook.com,[carolina rojas],[carolina.rojas.43@outlook.com]
2,3,CRM0177,20-179-048,Micaela Acosta,micaela.acosta.82@hotmail.com,1160551066,10/09/1970,55.0,f,Buenos Aires,E3100,Empresa,20/03/2022,379683.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,micaela acosta,20179048,micaela.acosta.82@hotmail.com,"[micaela acosta, micaela acosta]","[micaela.acosta.82@hotmail.com, <NA>]"
3,4,CRM0300,20315891,ANDRES BENITEZ,andres.benitez.68@hotmail.com,1137355219,17-11-07,18.0,Masculino,CABA,C1431,Particular,24-07-24,735737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,andres benitez,20315891,andres.benitez.68@hotmail.com,[andres benitez],[andres.benitez.68@hotmail.com]
4,5,CRM0198,20427454,Nicolas Rojas,nicolas.rojas.15@gmail.com,NaN,1971-12-28,54.0,D,Córdoba,E3100,Particular,14-03-25,570242.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nicolas rojas,20427454,nicolas.rojas.15@gmail.com,[nicolas rojas],[nicolas.rojas.15@gmail.com]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,525,NaN,NaN,Tomas A. Castro,tomasandrescastro35@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0102,rebote,6.0,3.0,tomas a. castro,<NA>,tomasandrescastro35@hotmail.com,NaN,[tomasandrescastro35@hotmail.com]
525,526,NaN,NaN,Tomas A. Torres,tomasandrestorres70@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00383,05-07-26,Consulta,1.0,NaN,NaN,NaN,NaN,tomas a. torres,<NA>,tomasandrestorres70@hotmail.com,NaN,[tomasandrestorres70@hotmail.com]
526,527,NaN,NaN,Tomas Romero,tomasromero76@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0320,activo,8.0,1.0,tomas romero,<NA>,tomasromero76@outlook.com,NaN,[tomasromero76@outlook.com]
527,528,NaN,NaN,Tomas Silva,tomassilva81@empresa.com.ar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N0162,activo,2.0,1.0,tomas silva,<NA>,tomassilva81@empresa.com.ar,NaN,[tomassilva81@empresa.com.ar]
528,529,NaN,NaN,Valentina Benitez,valentina.benitez.52@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V001440,20-08-25,20174.93,ARS,Tienda,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,valentina benitez,<NA>,valentina.benitez.52@outlook.com,NaN,[valentina.benitez.52@outlook.com]

In [142]:
df_total_final.isnull().sum()

cliente_id             0
crm_id               112
dni                   31
nombre                 0
email                 22
telefono             130
fecha_nacimiento     112
edad                 112
genero               117
provincia            112
codigo_postal        112
segmento             112
fecha_alta           112
ingreso_mensual      126
venta_id             450
fecha_compra         450
monto                450
moneda               450
canal                450
cantidad_items       450
ticket_id            520
fecha_ticket         520
tipo                 520
satisfaccion         523
suscriptor_id        505
estado               505
aperturas_90d        505
clicks_90d           505
nombre_limpio          0
dni_limpio            31
email_limpio          29
nombres_asociados     31
emails_asociados       0
dtype: int64

In [143]:
for index, i in enumerate(df_total_final["emails_asociados"]):
  lista = []
  for j in i:
    if pd.notna(j) and j not in lista:
      lista.append(j)
  df_total_final.at[index, "emails_asociados"] = lista

In [144]:
emails_conflictivos = []

dicc = {}

for i in df_total_final["emails_asociados"].explode().dropna():
    if i not in dicc.keys():
        dicc[i] = 1
    else:
        dicc[i] += 1

for i, j in dicc.items():
    if j > 1:
        print(i, j)
        emails_conflictivos.append(i)

camila.fernandez.61@empresa.com.ar 2

In [145]:
map_dni = {}

for i, fila in df_total_final.iterrows():
    if pd.notna(fila["dni_limpio"]):
        map_dni[fila["dni_limpio"]] = fila["cliente_id"]

In [146]:
map_dni

{'20003195': 1,
 '20084930': 2,
 '20179048': 3,
 '20315891': 4,
 '20427454': 5,
 '20450620': 6,
 '20456261': 7,
 '20568672': 8,
 '20597611': 9,
 '20655052': 10,
 '20684393': 11,
 '20724070': 12,
 '20743307': 13,
 '20745050': 14,
 '20758224': 15,
 '20800214': 16,
 '20993851': 17,
 '21005720': 18,
 '21005823': 19,
 '21015506': 20,
 '21133253': 21,
 '21235333': 22,
 '21351580': 23,
 '21444100': 24,
 '21637899': 25,
 '21719500': 26,
 '21724284': 27,
 '21747335': 28,
 '21832932': 29,
 '21857772': 30,
 '21965745': 31,
 '21980737': 32,
 '22186368': 33,
 '22264345': 34,
 '22370563': 35,
 '22384118': 36,
 '22496371': 37,
 '22512916': 38,
 '22536642': 39,
 '22600186': 40,
 '22710041': 41,
 '22799665': 42,
 '22856150': 43,
 '22919872': 44,
 '22931184': 45,
 '23085199': 46,
 '23159543': 47,
 '23168551': 48,
 '23178977': 49,
 '23347404': 50,
 '23357600': 51,
 '23457785': 52,
 '23469755': 53,
 '23508682': 54,
 '23535325': 55,
 '23547324': 56,
 '23592131': 57,
 '23605706': 58,
 '23723797': 59,
 '23743432': 60,
 '23769393': 61,
 '23824598': 62,
 '23923342': 63,
 '23992427': 64,
 '24090677': 65,
 '24102179': 66,
 '24190469': 67,
 '24201331': 68,
 '24204533': 69,
 '24226076': 70,
 '24235535': 71,
 '24309195': 72,
 '24469145': 73,
 '24483099': 74,
 '24574332': 75,
 '24733378': 76,
 '24753833': 77,
 '24760424': 78,
 '24773954': 79,
 '24833642': 80,
 '24901084': 81,
 '24928771': 82,
 '24949709': 83,
 '25071951': 84,
 '25075703': 85,
 '25153553': 86,
 '25193527': 87,
 '25316691': 88,
 '25342306': 89,
 '25428629': 90,
 '25502931': 91,
 '25519404': 92,
 '25584143': 93,
 '25723125': 94,
 '25907787': 95,
 '25978394': 96,
 '26097663': 97,
 '26345233': 98,
 '26365131': 99,
 '26418539': 100,
 '26479676': 101,
 '26496900': 102,
 '26510916': 103,
 '26580051': 104,
 '26686805': 105,
 '26689522': 106,
 '26731217': 107,
 '26772112': 108,
 '26913819': 109,
 '26927227': 110,
 '26947297': 111,
 '26962804': 112,
 '26999964': 113,
 '27095289': 114,
 '27131486': 115,
 '27249239': 116,
 '27491739': 117,
 '27567436': 118,
 '27573014': 119,
 '27580600': 120,
 '27667842': 121,
 '27693916': 122,
 '27697906': 123,
 '27701560': 124,
 '27853455': 125,
 '27878604': 126,
 '27879413': 127,
 '27925713': 128,
 '28006003': 129,
 '28010330': 130,
 '28095882': 131,
 '28146609': 132,
 '28241469': 133,
 '28264662': 134,
 '28288387': 135,
 '28373534': 136,
 '28542539': 137,
 '28608529': 138,
 '28693887': 139,
 '28714365': 140,
 '28718857': 141,
 '28794855': 142,
 '28862863': 143,
 '28864705': 144,
 '28876929': 145,
 '28968962': 146,
 '28984327': 147,
 '28986343': 148,
 '29042274': 149,
 '29153230': 150,
 '29261852': 151,
 '29272848': 152,
 '29316173': 153,
 '29602704': 154,
 '29668540': 155,
 '29710829': 156,
 '29726897': 157,
 '29800583': 158,
 '29804509': 159,
 '29814938': 160,
 '29830399': 161,
 '29859679': 162,
 '29907459': 163,
 '30030701': 164,
 '30072928': 165,
 '30165626': 166,
 '30204305': 167,
 '30232483': 168,
 '30326929': 169,
 '30341659': 170,
 '30387900': 171,
 '30419576': 172,
 '30503680': 173,
 '30521997': 174,
 '30530215': 175,
 '30543984': 176,
 '30640540': 177,
 '30870176': 178,
 '30922923': 179,
 '31017940': 180,
 '31129394': 181,
 '31214943': 182,
 '31218296': 183,
 '31280298': 184,
 '31416180': 185,
 '31429687': 186,
 '31431161': 187,
 '31452164': 188,
 '31475372': 189,
 '31483836': 190,
 '31517911': 191,
 '31570412': 192,
 '31753247': 193,
 '31845329': 194,
 '31979558': 195,
 '31982751': 196,
 '32043100': 197,
 '32170199': 198,
 '32201281': 199,
 '32240338': 200,
 '32253208': 201,
 '32337204': 202,
 '32359987': 203,
 '32484270': 204,
 '32537462': 205,
 '32546735': 206,
 '32605884': 207,
 '32607487': 208,
 '32681454': 209,
 '32727652': 210,
 '32760352': 211,
 '32802482': 212,
 '32859350': 213,
 '32874715': 214,
 '32909159': 215,
 '33022384': 216,
 '33225987': 217,
 '33437063': 218,
 '33460248': 219,
 '33526647': 220,
 '33606535': 221,
 '33654801': 222,
 '33679069': 223,
 '33757189': 224,
 '33849345': 225,
 '33884506': 226,
 '33941302': 227,
 '33986162': 228,
 '33987802': 229,
 '34263147': 230,
 '34373604': 231,
 '34388446': 232,
 '34521476': 233,
 '34538334': 234,
 '34569245': 235,
 '34586391': 236,
 '34606750': 237,
 '34664901': 238,
 '34744180': 239,
 '34821599': 240,
 '34917667': 241,
 '34918548': 242,
 '35078650': 243,
 '35094276': 244,
 '35098516': 245,
 '35102015': 246,
 '35148204': 247,
 '35173085': 248,
 '35189584': 249,
 '35192299': 250,
 '35202237': 251,
 '35207532': 252,
 '35286368': 253,
 '35309233': 254,
 '35315778': 255,
 '35358120': 256,
 '35377986': 257,
 '35380018': 258,
 '35382999': 259,
 '35398216': 260,
 '35442714': 261,
 '35457714': 262,
 '35470246': 263,
 '35493156': 264,
 '35509837': 265,
 '35578471': 266,
 '35699736': 267,
 '35730453': 268,
 '35769560': 269,
 '35773575': 270,
 '35774393': 271,
 '35776232': 272,
 '35841675': 273,
 '35955326': 274,
 '35960077': 275,
 '36009614': 276,
 '36101100': 277,
 '36184645': 278,
 '36206940': 279,
 '36287184': 280,
 '36322259': 281,
 '36339860': 282,
 '36354851': 283,
 '36439064': 284,
 '36602230': 285,
 '36685733': 286,
 '36704658': 287,
 '36798787': 288,
 '36836962': 289,
 '36852731': 290,
 '36860139': 291,
 '36970022': 292,
 '36991986': 293,
 '36996345': 294,
 '37041244': 295,
 '37064102': 296,
 '37167854': 297,
 '37193730': 298,
 '37216344': 299,
 '37231199': 300,
 '37232873': 301,
 '37300619': 302,
 '37410383': 303,
 '37549291': 304,
 '37563209': 305,
 '37626427': 306,
 '37722421': 307,
 '37730682': 308,
 '37751135': 309,
 '37864066': 310,
 '38114535': 311,
 '38322058': 312,
 '38347512': 313,
 '38390124': 314,
 '38461737': 315,
 '38468173': 316,
 '38504572': 317,
 '38686347': 318,
 '38690758': 319,
 '38811809': 320,
 '38825261': 321,
 '38868254': 322,
 '39012467': 323,
 '39060261': 324,
 '39132977': 325,
 '39303981': 326,
 '39385527': 327,
 '39484154': 328,
 '39520807': 329,
 '39551520': 330,
 '39650034': 331,
 '39841977': 332,
 '39906741': 333,
 '40088903': 334,
 '40119844': 335,
 '40251826': 336,
 '40273647': 337,
 '40333100': 338,
 '40343360': 339,
 '40540846': 340,
 '40542522': 341,
 '40625417': 342,
 '40665538': 343,
 '40724798': 344,
 '40794640': 345,
 '40836181': 346,
 '40854800': 347,
 '40887002': 348,
 '40893195': 349,
 '40946489': 350,
 '40983842': 351,
 '41080774': 352,
 '41157224': 353,
 '41171931': 354,
 '41229647': 355,
 '41284081': 356,
 '41302790': 357,
 '41354209': 358,
 '41474657': 359,
 '41509921': 360,
 '41528997': 361,
 '41532957': 362,
 '41604496': 363,
 '41609888': 364,
 '41668785': 365,
 '41691662': 366,
 '41736526': 367,
 '41766774': 368,
 '41806938': 369,
 '41831376': 370,
 '41859258': 371,
 '41982767': 372,
 '42000097': 373,
 '42007191': 374,
 '42223134': 375,
 '42230847': 376,
 '42252920': 377,
 '42304016': 378,
 '42385870': 379,
 '42448939': 380,
 '42489808': 381,
 '42567927': 382,
 '42637915': 383,
 '42639178': 384,
 '42640126': 385,
 '42645423': 386,
 '42677644': 387,
 '42777604': 388,
 '42904548': 389,
 '42919534': 390,
 '42983194': 391,
 '42995931': 392,
 '43226966': 393,
 '43331525': 394,
 '43384744': 395,
 '43478884': 396,
 '43505109': 397,
 '43558059': 398,
 '43576630': 399,
 '43596797': 400,
 '43780736': 401,
 '43818225': 402,
 '44010614': 403,
 '44191672': 404,
 '44205028': 405,
 '44232252': 406,
 '44308683': 407,
 '44413276': 408,
 '44521528': 409,
 '44685062': 410,
 '44753798': 411,
 '44756583': 412,
 '44763264': 413,
 '44846758': 414,
 '44873519': 415,
 '44971292': 416,
 '44974623': 417,
 '45047988': 418,
 '45089737': 419,
 '45131804': 420,
 '45174168': 421,
 '45187864': 422,
 '45217576': 423,
 '45343710': 424,
 '45399464': 425,
 '45444283': 426,
 '45489119': 427,
 '45490852': 428,
 '45516146': 429,
 '45613818': 430,
 '45632544': 431,
 '45696626': 432,
 '45728243': 433,
 '45811099': 434,
 '45813816': 435,
 '45940821': 436,
 '46014144': 437,
 '46187700': 438,
 '46369729': 439,
 '46370538': 440,
 '46448493': 441,
 '46449403': 442,
 '46557072': 443,
 '46599673': 444,
 '46642087': 445,
 '46715967': 446,
 '46741240': 447,
 '46780594': 448,
 '46785724': 449,
 '46801996': 450,
 '46881748': 451,
 '46992586': 452,
 '47055861': 453,
 '47143297': 454,
 '47169884': 455,
 '47195016': 456,
 '47206877': 457,
 '47336146': 458,
 '47418630': 459,
 '47454867': 460,
 '47496897': 461,
 '47529758': 462,
 '47537865': 463,
 '47587692': 464,
 '47643167': 465,
 '47649932': 466,
 '47688149': 467,
 '47719403': 468,
 '47730332': 469,
 '47740943': 470,
 '47775863': 471,
 '47828535': 472,
 '47829438': 473,
 '47883185': 474,
 '47941422': 475,
 '48093224': 476,
 '48103049': 477,
 '48154472': 478,
 '48263105': 479,
 '48268178': 480,
 '48328109': 481,
 '48378072': 482,
 '48414906': 483,
 '48461124': 484,
 '48638804': 485,
 '48744805': 486,
 '48939160': 487,
 '49008247': 488,
 '49071642': 489,
 '49145955': 490,
 '49292366': 491,
 '49294512': 492,
 '49353599': 493,
 '49803465': 494,
 '49806301': 495,
 '49827543': 496,
 '49924653': 497,
 '49976237': 498}

In [147]:
map_email = {}

for i, fila in df_total_final.iterrows():
    for email in fila["emails_asociados"]:
        if email not in emails_conflictivos:
            map_email[email] = fila["cliente_id"]

In [148]:
map_email

{'agustina.castro.90@hotmail.com': 1,
 'carolina.rojas.43@outlook.com': 2,
 'micaela.acosta.82@hotmail.com': 3,
 'andres.benitez.68@hotmail.com': 4,
 'nicolas.rojas.15@gmail.com': 5,
 'nicolas.franco.fernandez.26@outlook.com': 6,
 'andres.ramirez.83@empresa.com.ar': 7,
 'andresramirez83@empresa.com.ar': 7,
 'tomas.daniela.martinez.12@gmail.com': 8,
 'juan.flores.26@outlook.com': 9,
 'juanflores26@outlook.com': 9,
 'carolina.gomez.7@empresa.com.ar': 10,
 'maria.ramirez.46@empresa.com.ar': 11,
 'mariaramirez46@empresa.com.ar': 11,
 'daniela.laura.rojas.70@hotmail.com': 12,
 'tomas.rojas.38@gmail.com': 13,
 'nicolas.martin.alvarez.55@gmail.com': 14,
 'paula.rojas.35@hotmail.com': 15,
 'paularojas35@hotmail.com': 15,
 'camila.diaz.18@gmail.com': 16,
 'franco.tomas.ortiz.78@empresa.com.ar': 17,
 'carolina.rodriguez.40@empresa.com.ar': 18,
 'juan.gomez.31@gmail.com': 19,
 'valentina.ramirez.37@hotmail.com': 20,
 'natalia.rojas.15@hotmail.com': 21,
 'nataliarojas15@hotmail.com': 21,
 'franco.castro.72@gmail.com': 22,
 'laura.perez.45@gmail.com': 23,
 'franco.fernandez.70@outlook.com': 24,
 'pablo.rodriguez.1@empresa.com.ar': 25,
 'pablorodriguez1@empresa.com.ar': 25,
 'sofia.carolina.rojas.56@empresa.com.ar': 26,
 'martin.fernandez.75@empresa.com.ar': 27,
 'agustina.silva.20@hotmail.com': 28,
 'tomas.natalia.lopez.79@outlook.com': 29,
 'rocio.laura.ortiz.29@outlook.com': 30,
 'laura.romero.9@empresa.com.ar': 31,
 'diego.natalia.flores.83@empresa.com.ar': 32,
 'pablo.fernandez.0@empresa.com.ar': 33,
 'rocio.medina.77@empresa.com.ar': 34,
 'martin.alvarez.17@empresa.com.ar': 35,
 'maria.molina.80@gmail.com': 36,
 'juan.martinez.52@hotmail.com': 37,
 'sebastian.medina.17@gmail.com': 38,
 'carolina.gomez.69@hotmail.com': 40,
 'andres.fernandez.88@hotmail.com': 41,
 'leandro.juan.perez.84@empresa.com.ar': 42,
 'leandro.ruiz.2@outlook.com': 43,
 'diego.ortiz.89@outlook.com': 44,
 'tomas.andres.torres.70@hotmail.com': 45,
 'lucia.martinez.41@empresa.com.ar': 46,
 'tomas.castro.62@outlook.com': 47,
 'tomascastro62@outlook.com': 47,
 'valentina.benitez.51@empresa.com.ar': 48,
 'martin.tomas.martinez.57@hotmail.com': 49,
 'rocio.perez.86@hotmail.com': 50,
 'franco.diaz.3@outlook.com': 51,
 'juan.rojas.28@gmail.com': 52,
 'tomas.romero.54@outlook.com': 53,
 'natalia.rojas.23@outlook.com': 54,
 'laura.ramirez.12@gmail.com': 55,
 'martin.rodriguez.3@hotmail.com': 56,
 'martinrodriguez3@hotmail.com': 56,
 'federico.suarez.7@hotmail.com': 57,
 'agustina.silva.95@outlook.com': 58,
 'maria.benitez.28@outlook.com': 59,
 'camila.acosta.31@gmail.com': 60,
 'camilaacosta31@gmail.com': 60,
 'lucia.fernandez.73@gmail.com': 61,
 'diego.agustina.fernandez.81@outlook.com': 62,
 'camila.fernandez.42@outlook.com': 63,
 'laura.navarro.44@empresa.com.ar': 64,
 'federico.castro.43@outlook.com': 65,
 'nataliacastro42@gmail.com': 66,
 'lucia.perez.63@outlook.com': 67,
 'sebastian.romero.44@empresa.com.ar': 68,
 'laura.acosta.48@empresa.com.ar': 69,
 'matias.romero.39@gmail.com': 70,
 'federico.rodriguez.87@gmail.com': 71,
 'pablo.fernandez.37@empresa.com.ar': 72,
 'florencia.perez.36@empresa.com.ar': 73,
 'natalia.acosta.20@gmail.com': 74,
 'camila.navarro.72@hotmail.com': 75,
 'florencia.ramirez.11@hotmail.com': 76,
 'florenciaramirez11@hotmail.com': 76,
 'juan.diaz.65@outlook.com': 77,
 'florencia.romero.73@gmail.com': 78,
 'federico.andres.martinez.46@hotmail.com': 79,
 'federicoandresmartinez46@hotmail.com': 79,
 'florencia.silva.2@empresa.com.ar': 80,
 'daniela.flores.59@empresa.com.ar': 81,
 'paula.benitez.69@outlook.com': 82,
 'carolina.sanchez.49@outlook.com': 83,
 'franco.silva.32@hotmail.com': 84,
 'nicolas.navarro.3@hotmail.com': 86,
 'andres.gomez.89@gmail.com': 87,
 'lucia.castro.42@outlook.com': 88,
 'florencia.maria.silva.27@gmail.com': 89,
 'camila.ruiz.54@gmail.com': 90,
 'matias.rocio.diaz.24@gmail.com': 91,
 'matias.acosta.51@hotmail.com': 92,
 'carolina.molina.25@gmail.com': 93,
 'sofia.perez.93@empresa.com.ar': 94,
 'daniela.silva.1@hotmail.com': 95,
 'florencia.valentina.gomez.22@hotmail.com': 96,
 'florenciavalentinagomez22@hotmail.com': 96,
 'franco.martinez.4@gmail.com': 97,
 'florencia.joaquin.romero.9@outlook.com': 98,
 'julieta.ortiz.10@outlook.com': 99,
 'florencia.perez.60@outlook.com': 100,
 'sofia.leandro.romero.66@hotmail.com': 101,
 'federico.fernandez.39@empresa.com.ar': 102,
 'franco.castro.88@hotmail.com': 103,
 'andres.martinez.5@gmail.com': 104,
 'leandro.ruiz.11@gmail.com': 105,
 'diego.medina.1@gmail.com': 106,
 'valentina.romero.94@empresa.com.ar': 107,
 'federico.rojas.24@empresa.com.ar': 108,
 'valentinabenitez52@outlook.com': 109,
 'leandro.ortiz.36@hotmail.com': 110,
 'maria.julieta.acosta.26@hotmail.com': 111,
 'valentina.rodriguez.17@hotmail.com': 112,
 'valentinarodriguez17@hotmail.com': 112,
 'rocio.rodriguez.18@hotmail.com': 113,
 'rociorodriguez18@hotmail.com': 113,
 'florencia.sanchez.8@hotmail.com': 114,
 'florenciasanchez8@hotmail.com': 114,
 'micaela.martinez.28@empresa.com.ar': 115,
 'agustinanavarro93@empresa.com.ar': 116,
 'agustina.navarro.93@empresa.com.ar': 116,
 'valentina.lopez.62@empresa.com.ar': 117,
 'juan.tomas.molina.71@empresa.com.ar': 118,
 'maria.martinez.57@outlook.com': 119,
 'gonzalo.rojas.0@empresa.com.ar': 120,
 'joaquin.suarez.43@hotmail.com': 121,
 'leandro.molina.35@empresa.com.ar': 122,
 'sebastian.torres.95@hotmail.com': 123,
 'gonzalo.benitez.81@hotmail.com': 124,
 'florenciamariasilva27@gmail.com': 125,
 'leandro.natalia.molina.28@hotmail.com': 126,
 'natalia.sanchez.56@outlook.com': 127,
 'sebastian.lucia.medina.72@outlook.com': 128,
 'micaela.flores.34@hotmail.com': 129,
 'leandro.benitez.85@empresa.com.ar': 130,
 'julieta.benitez.71@hotmail.com': 131,
 'sebastian.rocio.rodriguez.91@outlook.com': 132,
 'carolina.navarro.40@gmail.com': 133,
 'martin.alvarez.77@gmail.com': 134,
 'camila.alvarez.82@outlook.com': 135,
 'carolina.ruiz.54@gmail.com': 136,
 'rocio.joaquin.rojas.58@outlook.com': 137,
 'micaela.suarez.48@empresa.com.ar': 138,
 'natalia.castro.64@empresa.com.ar': 139,
 'nataliacastro64@empresa.com.ar': 139,
 'lucia.martinez.36@empresa.com.ar': 140,
 'federico.martin.lopez.13@empresa.com.ar': 141,
 'pablo.martinez.86@gmail.com': 142,
 'carlos.gonzalo.navarro.64@outlook.com': 143,
 'laura.diaz.36@outlook.com': 144,
 'juan.castro.68@gmail.com': 145,
 'agustina.perez.57@empresa.com.ar': 146,
 'lucia.matias.acosta.54@outlook.com': 147,
 'luciamatiasacosta54@outlook.com': 147,
 'camila.natalia.benitez.5@hotmail.com': 148,
 'tomas.medina.57@outlook.com': 149,
 'camila.gomez.43@outlook.com': 150,
 'paula.castro.45@gmail.com': 151,
 'franco.martinez.22@outlook.com': 152,
 'martin.torres.72@hotmail.com': 153,
 'andres.joaquin.medina.5@gmail.com': 154,
 'andresjoaquinmedina5@gmail.com': 154,
 'joaquin.ortiz.1@outlook.com': 155,
 'joaquinortiz1@outlook.com': 155,
 'julieta.lopez.96@hotmail.com': 156,
 'micaela.julieta.fernandez.63@outlook.com': 157,
 'diego.sebastian.castro.4@hotmail.com': 158,
 'carolina.gomez.80@outlook.com': 159,
 'sebastian.benitez.52@gmail.com': 160,
 'florencia.navarro.60@outlook.com': 161,
 'lucia.diaz.27@empresa.com.ar': 162,
 'diego.ruiz.56@hotmail.com': 163,
 'camila.suarez.23@hotmail.com': 164,
 'gonzalo.carlos.ortiz.60@gmail.com': 165,
 'franco.flores.88@gmail.com': 166,
 'andres.navarro.27@outlook.com': 167,
 'andresnavarro27@outlook.com': 167,
 'pablo.sanchez.64@empresa.com.ar': 168,
 'sebastian.acosta.15@hotmail.com': 169,
 'sebastianacosta15@hotmail.com': 169,
 'joaquin.castro.1@hotmail.com': 170,
 'pablo.paula.flores.85@hotmail.com': 171,
 'pablopaulaflores85@hotmail.com': 171,
 'valentina.sanchez.53@outlook.com': 172,
 'valentinasanchez53@outlook.com': 172,
 'andres.rojas.6@empresa.com.ar': 173,
 'sebastian.flores.5@empresa.com.ar': 174,
 'micaela.gomez.46@hotmail.com': 175,
 'julieta.gomez.96@outlook.com': 176,
 'martin.romero.61@outlook.com': 177,
 'carolina.fernandez.74@gmail.com': 178,
 'valentina.castro.51@gmail.com': 179,
 'paula.sebastian.silva.25@empresa.com.ar': 180,
 'martin.gomez.62@hotmail.com': 181,
 'martingomez62@hotmail.com': 181,
 'juan.andres.acosta.59@hotmail.com': 182,
 'federico.lopez.29@outlook.com': 183,
 'leandro.ortiz.37@outlook.com': 184,
 'julieta.paula.molina.25@empresa.com.ar': 185,
 'agustina.rodriguez.81@gmail.com': 186,
 'pablo.ramirez.9@gmail.com': 187,
 'florencia.gonzalo.molina.73@gmail.com': 188,
 'nicolas.molina.27@empresa.com.ar': 189,
 'leandro.ortiz.34@hotmail.com': 190,
 'florencia.alvarez.14@hotmail.com': 191,
 'camila.flores.2@gmail.com': 192,
 'pablo.alvarez.51@empresa.com.ar': 193,
 'maria.andres.diaz.25@empresa.com.ar': 194,
 'carlos.nicolas.benitez.71@outlook.com': 195,
 'carlosnicolasbenitez71@outlook.com': 195,
 'sebastian.molina.5@gmail.com': 196,
 'federico.acosta.59@empresa.com.ar': 197,
 'leandro.sanchez.55@empresa.com.ar': 198,
 'nicolas.ruiz.56@hotmail.com': 199,
 'camila.acosta.49@hotmail.com': 200,
 'diego.acosta.93@gmail.com': 201,
 'agustina.florencia.silva.41@empresa.com.ar': 202,
 'leandro.ruiz.92@empresa.com.ar': 203,
 'leandroruiz92@empresa.com.ar': 203,
 'lucia.torres.66@outlook.com': 204,
 'joaquin.silva.92@gmail.com': 205,
 'joaquinsilva92@gmail.com': 205,
 'federico.matias.fernandez.20@gmail.com': 206,
 'valentina.alvarez.4@empresa.com.ar': 207,
 'martin.medina.89@hotmail.com': 208,
 'martin.acosta.15@gmail.com': 209,
 'juan.fernandez.17@outlook.com': 210,
 'rocio.diaz.20@outlook.com': 211,
 'rociodiaz20@outlook.com': 211,
 'matias.acosta.85@outlook.com': 212,
 'carlos.perez.13@gmail.com': 213,
 'rocio.sofia.acosta.60@hotmail.com': 214,
 'maria.castro.35@gmail.com': 215,
 'mariacastro35@gmail.com': 215,
 'paula.rojas.18@outlook.com': 216,
 'carlos.torres.89@gmail.com': 217,
 'sofia.medina.67@gmail.com': 218,
 'sofiamedina67@gmail.com': 218,
 'diego.lopez.3@hotmail.com': 219,
 'diegolopez3@hotmail.com': 219,
 'leandro.lopez.6@hotmail.com': 220,
 'nicolas.pablo.alvarez.82@hotmail.com': 221,
 'daniela.acosta.19@outlook.com': 222,
 'micaela.fernandez.91@empresa.com.ar': 223,
 'martin.castro.19@empresa.com.ar': 224,
 'rocio.pablo.diaz.67@hotmail.com': 225,
 'rocio.martinez.0@gmail.com': 226,
 'leandro.torres.67@empresa.com.ar': 227,
 'laura.rocio.molina.64@gmail.com': 228,
 'joaquin.carlos.ortiz.50@outlook.com': 229,
 'joaquin.romero.73@empresa.com.ar': 230,
 'andres.sanchez.71@gmail.com': 231,
 'natalia.julieta.rodriguez.21@outlook.com': 232,
 'natalia.martinez.33@gmail.com': 233,
 'micaela.molina.69@gmail.com': 234,
 'micaelamolina69@gmail.com': 234,
 'lucia.acosta.50@hotmail.com': 235,
 'luciaacosta50@hotmail.com': 235,
 'sofia.lopez.17@gmail.com': 236,
 'sofialopez17@gmail.com': 236,
 'gonzalo.diaz.79@hotmail.com': 237,
 'gonzalodiaz79@hotmail.com': 237,
 'matias.perez.6@gmail.com': 238,
 'matiasperez6@gmail.com': 238,
 'valentina.sanchez.31@hotmail.com': 239,
 'valentinasanchez31@hotmail.com': 239,
 'julieta.lopez.37@gmail.com': 240,
 'agustina.sanchez.5@outlook.com': 241,
 'agustinasanchez5@outlook.com': 241,
 'carolina.castro.88@empresa.com.ar': 242,
 'carolinacastro88@empresa.com.ar': 242,
 'micaela.ramirez.12@hotmail.com': 243,
 'maria.suarez.14@gmail.com': 244,
 'joaquin.silva.37@gmail.com': 245,
 'joaquinsilva37@gmail.com': 245,
 'maria.lucia.acosta.73@gmail.com': 246,
 'diego.benitez.72@gmail.com': 247,
 'juan.ortiz.87@outlook.com': 248,
 'lucia.medina.52@empresa.com.ar': 249,
 'rocio.natalia.perez.6@outlook.com': 250,
 'diego.suarez.33@outlook.com': 251,
 'rocio.silva.12@hotmail.com': 252,
 'diego.benitez.47@outlook.com': 253,
 'joaquin.lopez.14@hotmail.com': 254,
 'natalia.romero.78@gmail.com': 255,
 'leandro.castro.79@empresa.com.ar': 256,
 'leandrocastro79@empresa.com.ar': 256,
 'diego.fernandez.82@hotmail.com': 257,
 'daniela.andres.diaz.31@empresa.com.ar': 258,
 'julieta.carlos.navarro.18@hotmail.com': 259,
 'andres.ramirez.44@gmail.com': 260,
 'tomas.rojas.70@gmail.com': 261,
 'maria.ramirez.50@outlook.com': 262,
 'florencia.alvarez.15@outlook.com': 263,
 'martin.ruiz.29@outlook.com': 264,
 'joaquin.rodriguez.68@gmail.com': 265,
 'diego.navarro.49@empresa.com.ar': 266,
 'julieta.molina.58@outlook.com': 267,
 'julietamolina58@outlook.com': 267,
 'nicolas.rodriguez.14@outlook.com': 268,
 'paula.lopez.52@hotmail.com': 269,
 'rocio.ramirez.71@gmail.com': 270,
 'agustina.medina.83@hotmail.com': 271,
 'agustinamedina83@hotmail.com': 271,
 'juan.ramirez.30@empresa.com.ar': 272,
 'camila.rojas.41@hotmail.com': 273,
 'matias.torres.74@gmail.com': 274,
 'sofia.micaela.gomez.28@gmail.com': 275,
 'franco.gonzalo.sanchez.4@hotmail.com': 276,
 'diego.silva.96@outlook.com': 277,
 'camilafernandez61@empresa.com.ar': 278,
 'sebastian.torres.65@hotmail.com': 279,
 'rocio.rodriguez.39@hotmail.com': 280,
 'joaquin.sofia.martinez.66@outlook.com': 281,
 'joaquinsofiamartinez66@outlook.com': 281,
 'matias.perez.91@empresa.com.ar': 282,
 'federico.fernandez.29@gmail.com': 283,
 'julieta.acosta.11@outlook.com': 284,
 'paula.benitez.13@gmail.com': 285,
 'julieta.romero.61@gmail.com': 286,
 'lucia.castro.58@empresa.com.ar': 287,
 'sofia.tomas.ramirez.21@gmail.com': 288,
 'sofiatomasramirez21@gmail.com': 288,
 'julieta.sanchez.40@outlook.com': 289,
 'maria.rocio.castro.41@outlook.com': 290,
 'valentina.torres.75@gmail.com': 291,
 'agustina.navarro.84@gmail.com': 292,
 'diego.silva.75@gmail.com': 293,
 'federicoacosta93@outlook.com': 294,
 'federico.acosta.93@outlook.com': 294,
 'franco.sanchez.34@outlook.com': 295,
 'gonzalo.fernandez.44@gmail.com': 296,
 'pablo.rojas.78@empresa.com.ar': 297,
 'juan.franco.silva.55@hotmail.com': 298,
 'daniela.silva.44@empresa.com.ar': 299,
 'laura.molina.7@gmail.com': 300,
 'lauramolina7@gmail.com': 300,
 'pablo.suarez.40@gmail.com': 301,
 'matias.diaz.22@gmail.com': 302,
 'sofia.ortiz.94@gmail.com': 304,
 'joaquin.sanchez.47@gmail.com': 305,
 'carlos.suarez.91@gmail.com': 306,
 'laura.perez.69@outlook.com': 307,
 'lauraperez69@outlook.com': 307,
 'daniela.ramirez.50@outlook.com': 308,
 'laura.castro.86@outlook.com': 309,
 'lauracastro86@outlook.com': 309,
 'martin.silva.2@outlook.com': 310,
 'martinsilva2@outlook.com': 310,
 'sofia.molina.78@hotmail.com': 311,
 'natalia.fernandez.15@hotmail.com': 312,
 'nicolas.castro.93@gmail.com': 313,
 'maria.ortiz.21@outlook.com': 314,
 'sofia.sanchez.35@gmail.com': 315,
 'leandro.alvarez.48@outlook.com': 316,
 'gonzalo.navarro.85@empresa.com.ar': 317,
 'sofia.perez.92@gmail.com': 318,
 'leandro.suarez.80@outlook.com': 319,
 'leandro.navarro.95@empresa.com.ar': 320,
 'federico.benitez.45@outlook.com': 321,
 'natalia.sanchez.96@outlook.com': 322,
 'camila.ruiz.19@empresa.com.ar': 323,
 'daniela.lopez.32@empresa.com.ar': 324,
 'danielalopez32@empresa.com.ar': 324,
 'valentina.acosta.65@hotmail.com': 325,
 'valentinaacosta65@hotmail.com': 325,
 'federico.fernandez.77@outlook.com': 326,
 'juan.andres.diaz.9@empresa.com.ar': 327,
 'franco.rodriguez.75@gmail.com': 328,
 'tomas.rojas.86@empresa.com.ar': 329,
 'camila.rodriguez.24@empresa.com.ar': 330,
 'federico.perez.74@empresa.com.ar': 331,
 'diego.diaz.7@gmail.com': 332,
 'diegodiaz7@gmail.com': 332,
 'sofia.pablo.perez.90@gmail.com': 333,
 'martin.torres.49@hotmail.com': 334,
 'joaquin.martinez.60@hotmail.com': 335,
 'carlos.micaela.torres.8@gmail.com': 336,
 'sebastian.romero.47@empresa.com.ar': 337,
 'gonzalo.benitez.63@outlook.com': 338,
 'lucia.benitez.4@gmail.com': 339,
 'valentina.flores.12@hotmail.com': 340,
 'valentinaflores12@hotmail.com': 340,
 'tomas.silva.81@empresa.com.ar': 341,
 'federico.rodriguez.13@gmail.com': 342,
 'julieta.castro.74@outlook.com': 343,
 'micaela.medina.67@empresa.com.ar': 344,
 'julieta.rocio.alvarez.87@gmail.com': 345,
 'daniela.acosta.16@empresa.com.ar': 346,
 'maria.andres.romero.57@hotmail.com': 347,
 'laura.flores.94@outlook.com': 348,
 'agustina.benitez.49@empresa.com.ar': 349,
 'federico.gomez.43@hotmail.com': 350,
 'matias.silva.45@empresa.com.ar': 351,
 'paula.sofia.ortiz.86@outlook.com': 352,
 'leandro.diaz.10@outlook.com': 353,
 'camila.carolina.ortiz.84@empresa.com.ar': 354,
 'camilacarolinaortiz84@empresa.com.ar': 354,
 'sofia.camila.ruiz.10@outlook.com': 355,
 'sofiacamilaruiz10@outlook.com': 355,
 'agustina.paula.alvarez.42@hotmail.com': 356,
 'carlos.romero.22@outlook.com': 357,
 'carlosromero22@outlook.com': 357,
 'gonzalo.martinez.64@outlook.com': 358,
 'tomas.sanchez.59@outlook.com': 359,
 'valentina.ramirez.7@gmail.com': 360,
 'juan.silva.0@empresa.com.ar': 361,
 'martinacosta15@gmail.com': 362,
 'agustina.gomez.19@outlook.com': 363,
 'julieta.navarro.38@hotmail.com': 364,
 'julietanavarro38@hotmail.com': 364,
 'rocio.laura.ruiz.48@outlook.com': 365,
 'carlos.suarez.36@hotmail.com': 366,
 'leandro.agustina.benitez.90@gmail.com': 367,
 'martin.diaz.6@gmail.com': 368,
 'federico.juan.ruiz.79@empresa.com.ar': 369,
 'joaquin.navarro.4@gmail.com': 370,
 'joaquinnavarro4@gmail.com': 370,
 'micaela.diaz.62@empresa.com.ar': 371,
 'micaeladiaz62@empresa.com.ar': 371,
 'tomas.martinez.84@outlook.com': 372,
 'federico.suarez.19@outlook.com': 373,
 'pablo.fernandez.78@outlook.com': 374,
 'paula.martin.flores.53@gmail.com': 375,
 'paulamartinflores53@gmail.com': 375,
 'carolina.ramirez.90@outlook.com': 376,
 'gonzalo.fernandez.61@empresa.com.ar': 377,
 'nicolas.silva.22@outlook.com': 378,
 'nicolassilva22@outlook.com': 378,
 'agustina.camila.silva.10@hotmail.com': 379,
 'diego.rojas.9@gmail.com': 380,
 'leandro.romero.6@hotmail.com': 381,
 'camila.gonzalo.rodriguez.29@empresa.com.ar': 382,
 'lucia.perez.32@hotmail.com': 383,
 'camila.suarez.38@empresa.com.ar': 384,
 'matias.acosta.58@hotmail.com': 385,
 'paula.suarez.46@hotmail.com': 386,
 'micaela.franco.silva.87@gmail.com': 387,
 'diego.lopez.62@hotmail.com': 388,
 'camila.alvarez.40@hotmail.com': 389,
 'camilaalvarez40@hotmail.com': 389,
 'leandro.paula.rojas.11@outlook.com': 390,
 'camila.lopez.23@gmail.com': 391,
 'julieta.rodriguez.21@gmail.com': 392,
 'sofia.benitez.39@empresa.com.ar': 393,
 'valentina.ortiz.30@outlook.com': 394,
 'andres.torres.0@hotmail.com': 395,
 'federico.medina.76@outlook.com': 396,
 'sebastian.sofia.romero.38@empresa.com.ar': 397,
 'nicolas.lopez.16@gmail.com': 398,
 'nicolaslopez16@gmail.com': 398,
 'gonzalo.castro.11@hotmail.com': 399,
 'laura.suarez.65@gmail.com': 400,
 'tomas.andres.castro.35@hotmail.com': 401,
 'martin.gomez.41@hotmail.com': 402,
 'valentina.silva.14@outlook.com': 403,
 'tomas.joaquin.romero.8@empresa.com.ar': 404,
 'tomasjoaquinromero8@empresa.com.ar': 404,
 'camila.perez.30@gmail.com': 405,
 'camilaperez30@gmail.com': 405,
 'sebastian.medina.32@outlook.com': 406,
 'micaela.perez.33@hotmail.com': 407,
 'paula.ortiz.63@gmail.com': 408,
 'federico.acosta.77@gmail.com': 409,
 'diego.ortiz.16@outlook.com': 410,
 'diegoortiz16@outlook.com': 410,
 'natalia.rocio.castro.20@gmail.com': 411,
 'tomas.acosta.39@gmail.com': 412,
 'diego.castro.2@hotmail.com': 413,
 'daniela.acosta.75@hotmail.com': 414,
 'joaquin.ortiz.55@outlook.com': 415,
 'nicolas.perez.85@gmail.com': 416,
 'natalia.romero.12@empresa.com.ar': 417,
 'valentina.carlos.sanchez.23@empresa.com.ar': 418,
 'juan.alvarez.26@outlook.com': 419,
 'juanalvarez26@outlook.com': 419,
 'camila.ramirez.90@hotmail.com': 420,
 'gonzalo.acosta.77@outlook.com': 421,
 'matias.martinez.76@outlook.com': 422,
 'gonzalo.acosta.33@gmail.com': 423,
 'gonzaloacosta33@gmail.com': 423,
 'tomas.ortiz.50@empresa.com.ar': 424,
 'gonzalo.romero.53@gmail.com': 425,
 'sofia.lopez.92@hotmail.com': 426,
 'carlos.benitez.80@hotmail.com': 427,
 'federico.silva.55@gmail.com': 428,
 'gonzalo.martinez.31@outlook.com': 429,
 'gonzalo.alvarez.47@outlook.com': 430,
 'sebastian.martinez.14@hotmail.com': 431,
 'diego.joaquin.ramirez.30@hotmail.com': 432,
 'natalia.molina.63@outlook.com': 433,
 'micaela.laura.torres.7@outlook.com': 434,
 'micaelalauratorres7@outlook.com': 434,
 'agustina.benitez.96@empresa.com.ar': 435,
 'joaquin.flores.26@outlook.com': 436,
 'natalia.perez.88@hotmail.com': 437,
 'tomas.matias.lopez.11@empresa.com.ar': 438,
 'tomasmatiaslopez11@empresa.com.ar': 438,

### Ventas

In [149]:
df_ventas

,venta_id,dni,nombre,email,fecha_compra,monto,moneda,canal,cantidad_items
0,V000001,30387900,Pablo Flores,PABLO.PAULA.FLORES.85@HOTMAIL.COM,2025-07-24,64359.88,ARS,App,2
1,V000002,30.387.900,Pablo Flores,pablo.paula.flores.85@hotmail.com,09-03-24,111979.68,ARS,App,5
2,V000003,30-387-900,Pablo Paula Flores,pablo.paula.flores.85@hotmail.com,18/08/2024,16398.76,ARS,Web,2
3,V000004,30387900,Pablo Paula Flores,pablopaulaflores85@hotmail.com,10/05/2025,13055.74,ARS,Marketplace,2
4,V000005,27-131-486,Micaela Martinez,micaela.martinez.28@empresa.com.ar,03/08/2025,13676.59,ARS,App,3
...,...,...,...,...,...,...,...,...,...
1621,V001622,NaN,Martin Silva,martin.silva.2@outlook.com,2025-04-16,53683.58,ARS,Web,5
1622,V001623,37.864.066,Martin Silva,martin.silva.2@outlook.com,2024-12-06,30448.77,ARS,Web,3
1623,V001624,22.856.150,Leandro Ruiz,leandro.ruiz.2@outlook.com,2026-08-15,4800000.00,ARS,Web,86
1624,V001625,42.995.931,Julieta Rodríguez,julieta.rodriguez.21@gmail.com,2026-08-15,4800000.00,ARS,Web,86
1625,V001626,29.272.848,Franco Martínez,franco.martinez.22@outlook.com,2026-08-15,4800000.00,ARS,Web,86

In [150]:
df_ventas["dni_limpio"] = df_ventas["dni"].apply(limpiar_dni)
df_ventas["email_limpio"] = df_ventas["email"].apply(limpiar_email)

In [151]:
df_ventas

,venta_id,dni,nombre,email,fecha_compra,monto,moneda,canal,cantidad_items,dni_limpio,email_limpio
0,V000001,30387900,Pablo Flores,PABLO.PAULA.FLORES.85@HOTMAIL.COM,2025-07-24,64359.88,ARS,App,2,30387900,pablo.paula.flores.85@hotmail.com
1,V000002,30.387.900,Pablo Flores,pablo.paula.flores.85@hotmail.com,09-03-24,111979.68,ARS,App,5,30387900,pablo.paula.flores.85@hotmail.com
2,V000003,30-387-900,Pablo Paula Flores,pablo.paula.flores.85@hotmail.com,18/08/2024,16398.76,ARS,Web,2,30387900,pablo.paula.flores.85@hotmail.com
3,V000004,30387900,Pablo Paula Flores,pablopaulaflores85@hotmail.com,10/05/2025,13055.74,ARS,Marketplace,2,30387900,pablopaulaflores85@hotmail.com
4,V000005,27-131-486,Micaela Martinez,micaela.martinez.28@empresa.com.ar,03/08/2025,13676.59,ARS,App,3,27131486,micaela.martinez.28@empresa.com.ar
...,...,...,...,...,...,...,...,...,...,...,...
1621,V001622,NaN,Martin Silva,martin.silva.2@outlook.com,2025-04-16,53683.58,ARS,Web,5,<NA>,martin.silva.2@outlook.com
1622,V001623,37.864.066,Martin Silva,martin.silva.2@outlook.com,2024-12-06,30448.77,ARS,Web,3,37864066,martin.silva.2@outlook.com
1623,V001624,22.856.150,Leandro Ruiz,leandro.ruiz.2@outlook.com,2026-08-15,4800000.00,ARS,Web,86,22856150,leandro.ruiz.2@outlook.com
1624,V001625,42.995.931,Julieta Rodríguez,julieta.rodriguez.21@gmail.com,2026-08-15,4800000.00,ARS,Web,86,42995931,julieta.rodriguez.21@gmail.com
1625,V001626,29.272.848,Franco Martínez,franco.martinez.22@outlook.com,2026-08-15,4800000.00,ARS,Web,86,29272848,franco.martinez.22@outlook.com

In [152]:
# 1. DNI
df_ventas["cliente_id"] = df_ventas["dni_limpio"].map(map_dni)

por_dni = df_ventas["cliente_id"].notna().sum() # 1496

# 2. Email solamente para los que fallaron por DNI
sin_id = df_ventas["cliente_id"].isna()

df_ventas.loc[sin_id, "cliente_id"] = (df_ventas.loc[sin_id, "email_limpio"].map(map_email))

total = df_ventas["cliente_id"].notna().sum() # 1608
por_email = total - por_dni # 112

print("Por DNI:", por_dni)
print("Por email:", por_email)
print("Sin identificar:", df_ventas["cliente_id"].isna().sum())

Por DNI: 1496
Por email: 112
Sin identificar: 18

In [153]:
df_ventas

,venta_id,dni,nombre,email,fecha_compra,monto,moneda,canal,cantidad_items,dni_limpio,email_limpio,cliente_id
0,V000001,30387900,Pablo Flores,PABLO.PAULA.FLORES.85@HOTMAIL.COM,2025-07-24,64359.88,ARS,App,2,30387900,pablo.paula.flores.85@hotmail.com,171.0
1,V000002,30.387.900,Pablo Flores,pablo.paula.flores.85@hotmail.com,09-03-24,111979.68,ARS,App,5,30387900,pablo.paula.flores.85@hotmail.com,171.0
2,V000003,30-387-900,Pablo Paula Flores,pablo.paula.flores.85@hotmail.com,18/08/2024,16398.76,ARS,Web,2,30387900,pablo.paula.flores.85@hotmail.com,171.0
3,V000004,30387900,Pablo Paula Flores,pablopaulaflores85@hotmail.com,10/05/2025,13055.74,ARS,Marketplace,2,30387900,pablopaulaflores85@hotmail.com,171.0
4,V000005,27-131-486,Micaela Martinez,micaela.martinez.28@empresa.com.ar,03/08/2025,13676.59,ARS,App,3,27131486,micaela.martinez.28@empresa.com.ar,115.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1621,V001622,NaN,Martin Silva,martin.silva.2@outlook.com,2025-04-16,53683.58,ARS,Web,5,<NA>,martin.silva.2@outlook.com,310.0
1622,V001623,37.864.066,Martin Silva,martin.silva.2@outlook.com,2024-12-06,30448.77,ARS,Web,3,37864066,martin.silva.2@outlook.com,310.0
1623,V001624,22.856.150,Leandro Ruiz,leandro.ruiz.2@outlook.com,2026-08-15,4800000.00,ARS,Web,86,22856150,leandro.ruiz.2@outlook.com,43.0
1624,V001625,42.995.931,Julieta Rodríguez,julieta.rodriguez.21@gmail.com,2026-08-15,4800000.00,ARS,Web,86,42995931,julieta.rodriguez.21@gmail.com,392.0
1625,V001626,29.272.848,Franco Martínez,franco.martinez.22@outlook.com,2026-08-15,4800000.00,ARS,Web,86,29272848,franco.martinez.22@outlook.com,152.0

In [154]:
#df_ventas = df_ventas[["cliente_id"] + [col for col in df_ventas.columns if col != "cliente_id"]]
df_ventas["cliente_id"] = df_ventas["cliente_id"].astype("Int64")
df_ventas.head()

,venta_id,dni,nombre,email,fecha_compra,monto,moneda,canal,cantidad_items,dni_limpio,email_limpio,cliente_id
0,V000001,30387900,Pablo Flores,PABLO.PAULA.FLORES.85@HOTMAIL.COM,2025-07-24,64359.88,ARS,App,2,30387900,pablo.paula.flores.85@hotmail.com,171
1,V000002,30.387.900,Pablo Flores,pablo.paula.flores.85@hotmail.com,09-03-24,111979.68,ARS,App,5,30387900,pablo.paula.flores.85@hotmail.com,171
2,V000003,30-387-900,Pablo Paula Flores,pablo.paula.flores.85@hotmail.com,18/08/2024,16398.76,ARS,Web,2,30387900,pablo.paula.flores.85@hotmail.com,171
3,V000004,30387900,Pablo Paula Flores,pablopaulaflores85@hotmail.com,10/05/2025,13055.74,ARS,Marketplace,2,30387900,pablopaulaflores85@hotmail.com,171
4,V000005,27-131-486,Micaela Martinez,micaela.martinez.28@empresa.com.ar,03/08/2025,13676.59,ARS,App,3,27131486,micaela.martinez.28@empresa.com.ar,115

In [155]:
df_ventas.columns

Index(['venta_id', 'dni', 'nombre', 'email', 'fecha_compra', 'monto', 'moneda',
       'canal', 'cantidad_items', 'dni_limpio', 'email_limpio', 'cliente_id'],
      dtype='object')

In [156]:
df_ventas[["venta_id", "fecha_compra", "monto", "moneda", "canal", "cantidad_items"]].isna().sum()

venta_id          0
fecha_compra      0
monto             0
moneda            0
canal             0
cantidad_items    0
dtype: int64

In [157]:
df_ventas.describe().T

,count,mean,std,min,25%,50%,75%,max
monto,1626.0,61380.133782,216544.564105,8.96,17917.315,31629.22,59329.7,4800000.0
cantidad_items,1626.0,2.466175,3.822737,1.0,1.0,2.0,3.0,86.0
cliente_id,1608.0,249.31592,148.004721,1.0,118.0,246.0,380.0,529.0

In [158]:
df_ventas["moneda"].unique()

array(['ARS', 'USD'], dtype=object)

In [159]:
df_ventas.groupby("moneda")["monto"].describe()

,count,mean,std,min,25%,50%,75%,max
moneda,,,,,,,,
ARS,1608.0,62066.758924,217656.072074,2500.00,18209.175,32169.34,60131.7275,4800000.00
USD,18.0,41.621111,61.109652,8.96,14.245,17.90,36.3975,262.34

In [160]:
df_ventas["moneda"].value_counts(dropna=False)

moneda
ARS    1608
USD      18
Name: count, dtype: int64

In [161]:
df_ventas["fecha_compra"].head(10)

0    2025-07-24
1      09-03-24
2    18/08/2024
3    10/05/2025
4    03/08/2025
5    2025-08-11
6    2024-03-10
7    04/03/2024
8      05-05-26
9    2025-07-16
Name: fecha_compra, dtype: object

#### Se nos presenta el siguiente problema: Las fechas no están normalizadas, y hay pocos montos en dolares que deberíamos pasar a pesos, pero antes de hacer la conversión debemos establecer a que precio estaba el dolar en el momento de la compra (aproximadamente)